// Mock Users
export const mockUsers = [
  {
    id: 1,
    email: 'admin@eventpub.com',
    password: 'admin123',
    role: 'admin',
    name: 'Admin User',
    avatar: 'https://ui-avatars.com/api/?name=Admin+User&background=667eea&color=fff'
  },
  {
    id: 2,
    email: 'techcorp@company.com',
    password: 'company123',
    role: 'company',
    name: 'TechCorp Events',
    companyName: 'TechCorp',
    description: 'Leading technology events organizer',
    avatar: 'https://ui-avatars.com/api/?name=TechCorp&background=764ba2&color=fff',
    status: 'approved'
  },
  {
    id: 3,
    email: 'creative@company.com',
    password: 'company123',
    role: 'company',
    name: 'Creative Studios',
    companyName: 'Creative Studios',
    description: 'Art and design event specialists',
    avatar: 'https://ui-avatars.com/api/?name=Creative+Studios&background=f5576c&color=fff',
    status: 'approved'
  },
  {
    id: 4,
    email: 'user@example.com',
    password: 'user123',
    role: 'public',
    name: 'John Doe',
    avatar: 'https://ui-avatars.com/api/?name=John+Doe&background=4facfe&color=fff',
    registeredEvents: [1, 3]
  }
];

// Mock Events
export const mockEvents = [
  {
    id: 1,
    title: 'Tech Summit 2025',
    description: 'Join us for the biggest technology conference of the year. Featuring keynotes from industry leaders, hands-on workshops, and networking opportunities.',
    category: 'Technology',
    date: '2026-02-15',
    time: '09:00:00',
    location: 'Convention Center, New York',
    latitude: 40.7580,
    longitude: -73.9855,
    type: 'venue',
    capacity: 500,
    registered: 342,
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=500&fit=crop',
    companyId: 2,
    companyName: 'TechCorp Events',
    status: 'published',
    featured: true,
    createdAt: '2024-12-01'
  },
  {
    id: 2,
    title: 'Digital Marketing Masterclass',
    description: 'Learn the latest digital marketing strategies from experts. Cover SEO, social media, content marketing, and analytics.',
    category: 'Business',
    date: '2026-02-20',
    time: '14:00:00',
    location: 'Online',
    type: 'online',
    capacity: 1000,
    registered: 756,
    image: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&h=500&fit=crop',
    companyId: 2,
    companyName: 'TechCorp Events',
    status: 'published',
    featured: true,
    createdAt: '2024-12-05',
    youtubeStreamId: 'jfKfPfyJRdk' // Sample YouTube video ID
  },
  {
    id: 3,
    title: 'Art & Design Expo',
    description: 'Explore the latest trends in art and design. Exhibition featuring works from emerging and established artists.',
    category: 'Arts',
    date: '2026-03-01',
    time: '10:00:00',
    location: 'Art Gallery, Los Angeles',
    latitude: 34.0522,
    longitude: -118.2437,
    type: 'venue',
    capacity: 300,
    registered: 189,
    image: 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: false,
    createdAt: '2024-12-08'
  },
  {
    id: 4,
    title: 'Startup Pitch Night',
    description: 'Watch innovative startups pitch their ideas to investors. Network with entrepreneurs and venture capitalists.',
    category: 'Business',
    date: '2026-02-25',
    time: '18:00:00',
    location: 'Innovation Hub, San Francisco',
    latitude: 37.7749,
    longitude: -122.4194,
    type: 'venue',
    capacity: 200,
    registered: 145,
    image: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&h=500&fit=crop',
    companyId: 2,
    companyName: 'TechCorp Events',
    status: 'published',
    featured: false,
    createdAt: '2024-12-10'
  },
  {
    id: 5,
    title: 'Music Festival 2025',
    description: 'Three days of live music featuring top artists from around the world. Food, drinks, and unforgettable experiences.',
    category: 'Entertainment',
    date: '2026-03-15',
    time: '12:00:00',
    location: 'Central Park, Chicago',
    latitude: 41.8781,
    longitude: -87.6298,
    type: 'venue',
    capacity: 5000,
    registered: 3421,
    image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: true,
    createdAt: '2024-12-12'
  },
  {
    id: 6,
    title: 'Health & Wellness Workshop',
    description: 'Comprehensive workshop on mental and physical wellness. Yoga, meditation, nutrition guidance, and more.',
    category: 'Health',
    date: '2026-03-10',
    time: '08:00:00',
    location: 'Wellness Center, Miami',
    latitude: 25.7617,
    longitude: -80.1918,
    type: 'venue',
    capacity: 150,
    registered: 98,
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: false,
    createdAt: '2024-12-15'
  },
  {
    id: 7,
    title: 'AI & Machine Learning Conference',
    description: 'Deep dive into artificial intelligence and machine learning. Latest research, applications, and future trends.',
    category: 'Technology',
    date: '2026-03-20',
    time: '09:00:00',
    location: 'Online',
    type: 'online',
    capacity: 2000,
    registered: 1567,
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&h=500&fit=crop',
    companyId: 2,
    companyName: 'TechCorp Events',
    status: 'published',
    featured: false,
    createdAt: '2024-12-16',
    youtubeStreamId: 'dQw4w9WgXcQ'
  },
  {
    id: 8,
    title: 'Food & Wine Festival',
    description: 'Culinary experience featuring renowned chefs and sommeliers. Tastings, cooking demos, and wine pairings.',
    category: 'Food',
    date: '2026-04-01',
    time: '17:00:00',
    location: 'Grand Hotel, Boston',
    latitude: 42.3601,
    longitude: -71.0589,
    type: 'venue',
    capacity: 400,
    registered: 245,
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: false,
    createdAt: '2024-12-17'
  },
  {
    id: 9,
    title: 'Blockchain Summit',
    description: 'Explore the future of blockchain technology and cryptocurrency. Expert panels, workshops, and networking.',
    category: 'Technology',
    date: '2026-04-10',
    time: '10:00:00',
    location: 'Tech Hub, Austin',
    latitude: 30.2672,
    longitude: -97.7431,
    type: 'venue',
    capacity: 600,
    registered: 423,
    image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=500&fit=crop',
    companyId: 2,
    companyName: 'TechCorp Events',
    status: 'published',
    featured: true,
    createdAt: '2024-12-18'
  },
  {
    id: 10,
    title: 'Photography Workshop',
    description: 'Master the art of photography with professional photographers. Hands-on sessions covering composition, lighting, and editing.',
    category: 'Arts',
    date: '2026-04-15',
    time: '09:00:00',
    location: 'Art Studio, Seattle',
    latitude: 47.6062,
    longitude: -122.3321,
    type: 'venue',
    capacity: 80,
    registered: 67,
    image: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: false,
    createdAt: '2024-12-19'
  },
  {
    id: 11,
    title: 'Marathon & Run Event',
    description: 'Annual city marathon with 5K, 10K, and full marathon options. All fitness levels welcome!',
    category: 'Sports',
    date: '2026-04-20',
    time: '06:00:00',
    location: 'City Center, Denver',
    latitude: 39.7392,
    longitude: -104.9903,
    type: 'venue',
    capacity: 3000,
    registered: 2156,
    image: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: true,
    createdAt: '2024-12-20'
  },
  {
    id: 12,
    title: 'Entrepreneurship Bootcamp',
    description: 'Intensive 3-day bootcamp for aspiring entrepreneurs. Learn business planning, funding strategies, and growth hacking.',
    category: 'Business',
    date: '2026-04-25',
    time: '09:00:00',
    location: 'Innovation Center, Portland',
    latitude: 45.5152,
    longitude: -122.6784,
    type: 'venue',
    capacity: 120,
    registered: 89,
    image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&h=500&fit=crop',
    companyId: 2,
    companyName: 'TechCorp Events',
    status: 'published',
    featured: false,
    createdAt: '2024-12-21'
  },
  {
    id: 13,
    title: 'Jazz Night Live',
    description: 'Evening of smooth jazz featuring local and international artists. Dinner and drinks available.',
    category: 'Entertainment',
    date: '2026-05-01',
    time: '19:00:00',
    location: 'Jazz Club, New Orleans',
    latitude: 29.9511,
    longitude: -90.0715,
    type: 'venue',
    capacity: 250,
    registered: 198,
    image: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: false,
    createdAt: '2024-12-22'
  },
  {
    id: 14,
    title: 'Yoga & Meditation Retreat',
    description: 'Weekend retreat focused on mindfulness, yoga, and meditation. Escape the city and find your zen.',
    category: 'Health',
    date: '2026-05-05',
    time: '07:00:00',
    location: 'Retreat Center, Phoenix',
    latitude: 33.4484,
    longitude: -112.0740,
    type: 'venue',
    capacity: 100,
    registered: 76,
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: false,
    createdAt: '2024-12-23'
  },
  {
    id: 15,
    title: 'Craft Beer Festival',
    description: 'Sample craft beers from over 50 local breweries. Live music, food trucks, and brewery tours.',
    category: 'Food',
    date: '2026-05-10',
    time: '14:00:00',
    location: 'Brewery District, Nashville',
    latitude: 36.1627,
    longitude: -86.7816,
    type: 'venue',
    capacity: 800,
    registered: 612,
    image: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: true,
    createdAt: '2024-12-24'
  },
  {
    id: 16,
    title: 'Web Development Workshop',
    description: 'Learn modern web development with React, Node.js, and MongoDB. Build a full-stack application.',
    category: 'Education',
    date: '2026-05-15',
    time: '10:00:00',
    location: 'Tech Campus, Atlanta',
    latitude: 33.7490,
    longitude: -84.3880,
    type: 'venue',
    capacity: 150,
    registered: 134,
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=500&fit=crop',
    companyId: 2,
    companyName: 'TechCorp Events',
    status: 'published',
    featured: false,
    createdAt: '2024-12-25'
  },
  // International Events
  {
    id: 17,
    title: 'London Tech Summit',
    description: 'Europe\'s largest technology conference bringing together innovators, investors, and industry leaders.',
    category: 'Technology',
    date: '2026-06-01',
    time: '09:00:00',
    location: 'ExCeL London, United Kingdom',
    latitude: 51.5074,
    longitude: -0.1278,
    type: 'venue',
    capacity: 2500,
    registered: 1876,
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=500&fit=crop',
    companyId: 2,
    companyName: 'TechCorp Events',
    status: 'published',
    featured: true,
    createdAt: '2024-12-26'
  },
  {
    id: 18,
    title: 'Paris Fashion Week',
    description: 'Haute couture and ready-to-wear fashion shows from world-renowned designers. The pinnacle of fashion.',
    category: 'Arts',
    date: '2026-06-10',
    time: '14:00:00',
    location: 'Grand Palais, Paris, France',
    latitude: 48.8566,
    longitude: 2.3522,
    type: 'venue',
    capacity: 1200,
    registered: 987,
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: true,
    createdAt: '2024-12-27'
  },
  {
    id: 19,
    title: 'Tokyo Anime Expo',
    description: 'Celebrate Japanese anime and manga culture. Cosplay contests, artist panels, and exclusive previews.',
    category: 'Entertainment',
    date: '2026-06-15',
    time: '10:00:00',
    location: 'Tokyo Big Sight, Japan',
    latitude: 35.6762,
    longitude: 139.6503,
    type: 'venue',
    capacity: 5000,
    registered: 4234,
    image: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: true,
    createdAt: '2024-12-28'
  },
  {
    id: 20,
    title: 'Dubai Business Forum',
    description: 'International business networking event. Connect with entrepreneurs and investors from the Middle East.',
    category: 'Business',
    date: '2026-06-20',
    time: '08:00:00',
    location: 'Burj Khalifa, Dubai, UAE',
    latitude: 25.2048,
    longitude: 55.2708,
    type: 'venue',
    capacity: 800,
    registered: 645,
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=500&fit=crop',
    companyId: 2,
    companyName: 'TechCorp Events',
    status: 'published',
    featured: false,
    createdAt: '2024-12-29'
  },
  {
    id: 21,
    title: 'Sydney Opera Festival',
    description: 'World-class opera performances in the iconic Sydney Opera House. A celebration of classical music.',
    category: 'Entertainment',
    date: '2026-07-01',
    time: '19:00:00',
    location: 'Sydney Opera House, Australia',
    latitude: -33.8688,
    longitude: 151.2093,
    type: 'venue',
    capacity: 1500,
    registered: 1289,
    image: 'https://images.unsplash.com/photo-1523731407965-2430cd12f5e4?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: true,
    createdAt: '2024-12-30'
  },
  {
    id: 22,
    title: 'Berlin Music Festival',
    description: 'Electronic music festival featuring top DJs and producers from around the world. Dance until dawn.',
    category: 'Entertainment',
    date: '2026-07-10',
    time: '18:00:00',
    location: 'Tempelhof Airport, Berlin, Germany',
    latitude: 52.5200,
    longitude: 13.4050,
    type: 'venue',
    capacity: 8000,
    registered: 6543,
    image: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: true,
    createdAt: '2024-12-31'
  },
  {
    id: 23,
    title: 'Singapore FinTech Summit',
    description: 'Asia\'s premier financial technology conference. Blockchain, digital banking, and payment innovations.',
    category: 'Technology',
    date: '2026-07-15',
    time: '09:00:00',
    location: 'Marina Bay Sands, Singapore',
    latitude: 1.3521,
    longitude: 103.8198,
    type: 'venue',
    capacity: 1500,
    registered: 1123,
    image: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&h=500&fit=crop',
    companyId: 2,
    companyName: 'TechCorp Events',
    status: 'published',
    featured: true,
    createdAt: '2025-01-01'
  },
  {
    id: 24,
    title: 'Barcelona Food Festival',
    description: 'Mediterranean cuisine celebration. Tapas, paella, and wine from Spain\'s best chefs and vineyards.',
    category: 'Food',
    date: '2026-07-20',
    time: '12:00:00',
    location: 'La Rambla, Barcelona, Spain',
    latitude: 41.3851,
    longitude: 2.1734,
    type: 'venue',
    capacity: 2000,
    registered: 1567,
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: false,
    createdAt: '2025-01-02'
  },
  {
    id: 25,
    title: 'Mumbai Startup Conference',
    description: 'India\'s largest startup ecosystem event. Pitch competitions, investor meetings, and mentorship.',
    category: 'Business',
    date: '2026-08-01',
    time: '10:00:00',
    location: 'BKC Convention Center, Mumbai, India',
    latitude: 19.0760,
    longitude: 72.8777,
    type: 'venue',
    capacity: 1000,
    registered: 789,
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=500&fit=crop',
    companyId: 2,
    companyName: 'TechCorp Events',
    status: 'published',
    featured: false,
    createdAt: '2025-01-03'
  },
  {
    id: 26,
    title: 'Rio Carnival Experience',
    description: 'Join the world\'s biggest carnival celebration. Samba parades, street parties, and Brazilian culture.',
    category: 'Entertainment',
    date: '2026-02-15',
    time: '15:00:00',
    location: 'Sambadrome, Rio de Janeiro, Brazil',
    latitude: -22.9068,
    longitude: -43.1729,
    type: 'venue',
    capacity: 10000,
    registered: 8765,
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: true,
    createdAt: '2025-01-04'
  },
  {
    id: 27,
    title: 'Cape Town Wine Tasting',
    description: 'South African wine experience featuring award-winning vineyards from the Western Cape region.',
    category: 'Food',
    date: '2026-08-10',
    time: '16:00:00',
    location: 'Waterfront, Cape Town, South Africa',
    latitude: -33.9249,
    longitude: 18.4241,
    type: 'venue',
    capacity: 500,
    registered: 387,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: false,
    createdAt: '2025-01-05'
  },
  {
    id: 28,
    title: 'Amsterdam Blockchain Week',
    description: 'Europe\'s crypto and blockchain hub. Workshops, hackathons, and networking with Web3 pioneers.',
    category: 'Technology',
    date: '2026-08-15',
    time: '09:00:00',
    location: 'RAI Amsterdam, Netherlands',
    latitude: 52.3676,
    longitude: 4.9041,
    type: 'venue',
    capacity: 1200,
    registered: 934,
    image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=500&fit=crop',
    companyId: 2,
    companyName: 'TechCorp Events',
    status: 'published',
    featured: true,
    createdAt: '2025-01-06'
  },
  {
    id: 29,
    title: 'Seoul K-Pop Festival',
    description: 'Experience Korean pop culture with live performances, fan meetings, and K-beauty workshops.',
    category: 'Entertainment',
    date: '2026-08-20',
    time: '17:00:00',
    location: 'Olympic Stadium, Seoul, South Korea',
    latitude: 37.5665,
    longitude: 126.9780,
    type: 'venue',
    capacity: 6000,
    registered: 5234,
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: true,
    createdAt: '2025-01-07'
  },
  {
    id: 30,
    title: 'Toronto Film Festival',
    description: 'International film festival showcasing independent and mainstream cinema from around the globe.',
    category: 'Arts',
    date: '2026-09-01',
    time: '18:00:00',
    location: 'TIFF Bell Lightbox, Toronto, Canada',
    latitude: 43.6532,
    longitude: -79.3832,
    type: 'venue',
    capacity: 800,
    registered: 687,
    image: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: false,
    createdAt: '2025-01-08'
  },
  {
    id: 31,
    title: 'Istanbul Art Biennale',
    description: 'Contemporary art exhibition featuring artists from Turkey and the Mediterranean region.',
    category: 'Arts',
    date: '2026-09-10',
    time: '11:00:00',
    location: 'Istanbul Modern, Turkey',
    latitude: 41.0082,
    longitude: 28.9784,
    type: 'venue',
    capacity: 600,
    registered: 456,
    image: 'https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: false,
    createdAt: '2025-01-09'
  },
  // Sri Lanka Events
  {
    id: 32,
    title: 'Colombo Tech Summit',
    description: 'Sri Lanka\'s premier technology conference featuring AI, blockchain, and software development innovations.',
    category: 'Technology',
    date: '2026-09-15',
    time: '09:00:00',
    location: 'BMICH, Colombo, Sri Lanka',
    latitude: 6.9271,
    longitude: 79.8612,
    type: 'venue',
    capacity: 1500,
    registered: 1123,
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=500&fit=crop',
    companyId: 2,
    companyName: 'TechCorp Events',
    status: 'published',
    featured: true,
    createdAt: '2025-01-10'
  },
  {
    id: 33,
    title: 'Kandy Cultural Festival',
    description: 'Celebrate Sri Lankan heritage with traditional dance, music, and cultural performances in the historic city of Kandy.',
    category: 'Arts',
    date: '2026-09-20',
    time: '17:00:00',
    location: 'Temple of the Tooth, Kandy, Sri Lanka',
    latitude: 7.2906,
    longitude: 80.6337,
    type: 'venue',
    capacity: 800,
    registered: 654,
    image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: true,
    createdAt: '2025-01-11'
  },
  {
    id: 34,
    title: 'Galle Food & Spice Festival',
    description: 'Experience authentic Sri Lankan cuisine and spices. Cooking demonstrations, tastings, and culinary workshops.',
    category: 'Food',
    date: '2026-10-01',
    time: '11:00:00',
    location: 'Galle Fort, Galle, Sri Lanka',
    latitude: 6.0535,
    longitude: 80.2210,
    type: 'venue',
    capacity: 600,
    registered: 478,
    image: 'https://images.unsplash.com/photo-1596040033229-a0b3b7d3c0f0?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: false,
    createdAt: '2025-01-12'
  },
  {
    id: 35,
    title: 'Colombo Startup Expo',
    description: 'Showcase of innovative startups from Sri Lanka. Pitch competitions, investor networking, and mentorship sessions.',
    category: 'Business',
    date: '2026-10-05',
    time: '10:00:00',
    location: 'Waters Edge, Colombo, Sri Lanka',
    latitude: 6.9271,
    longitude: 79.8612,
    type: 'venue',
    capacity: 500,
    registered: 389,
    image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&h=500&fit=crop',
    companyId: 2,
    companyName: 'TechCorp Events',
    status: 'published',
    featured: false,
    createdAt: '2025-01-13'
  },
  {
    id: 36,
    title: 'Colombo Marathon',
    description: 'Annual city marathon with 5K, 10K, half marathon, and full marathon categories. Run along the scenic coastline.',
    category: 'Sports',
    date: '2026-10-10',
    time: '06:00:00',
    location: 'Galle Face Green, Colombo, Sri Lanka',
    latitude: 6.9271,
    longitude: 79.8467,
    type: 'venue',
    capacity: 5000,
    registered: 3876,
    image: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: true,
    createdAt: '2025-01-14'
  },
  {
    id: 37,
    title: 'Ayurveda & Wellness Retreat',
    description: 'Traditional Sri Lankan Ayurvedic treatments, yoga, meditation, and holistic wellness practices.',
    category: 'Health',
    date: '2026-10-15',
    time: '08:00:00',
    location: 'Bentota Beach, Bentota, Sri Lanka',
    latitude: 6.4260,
    longitude: 79.9957,
    type: 'venue',
    capacity: 200,
    registered: 156,
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: false,
    createdAt: '2025-01-15'
  },
  {
    id: 38,
    title: 'Colombo Jazz Night',
    description: 'Evening of smooth jazz featuring local and international artists. Dinner, drinks, and live performances.',
    category: 'Entertainment',
    date: '2026-10-20',
    time: '19:00:00',
    location: 'Cinnamon Grand, Colombo, Sri Lanka',
    latitude: 6.9271,
    longitude: 79.8612,
    type: 'venue',
    capacity: 300,
    registered: 234,
    image: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: false,
    createdAt: '2025-01-16'
  },
  {
    id: 39,
    title: 'Digital Marketing Workshop',
    description: 'Learn SEO, social media marketing, content strategy, and analytics. Hands-on training for businesses.',
    category: 'Education',
    date: '2026-10-25',
    time: '09:00:00',
    location: 'IFS Tower, Colombo, Sri Lanka',
    latitude: 6.9271,
    longitude: 79.8612,
    type: 'venue',
    capacity: 150,
    registered: 127,
    image: 'https://images.unsplash.com/photo-1432888622747-4eb9a8f2c293?w=800&h=500&fit=crop',
    companyId: 2,
    companyName: 'TechCorp Events',
    status: 'published',
    featured: false,
    createdAt: '2025-01-17'
  },
  {
    id: 40,
    title: 'Colombo Art Exhibition',
    description: 'Contemporary art showcase featuring Sri Lankan artists. Paintings, sculptures, and mixed media installations.',
    category: 'Arts',
    date: '2026-11-01',
    time: '14:00:00',
    location: 'Lionel Wendt Art Centre, Colombo, Sri Lanka',
    latitude: 6.9018,
    longitude: 79.8585,
    type: 'venue',
    capacity: 400,
    registered: 298,
    image: 'https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: false,
    createdAt: '2025-01-18'
  },
  {
    id: 41,
    title: 'Colombo Music Festival',
    description: 'Three-day music festival featuring local and international artists. Rock, pop, EDM, and traditional music.',
    category: 'Entertainment',
    date: '2026-11-05',
    time: '16:00:00',
    location: 'Sugathadasa Stadium, Colombo, Sri Lanka',
    latitude: 6.9271,
    longitude: 79.8612,
    type: 'venue',
    capacity: 10000,
    registered: 7654,
    image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&h=500&fit=crop',
    companyId: 3,
    companyName: 'Creative Studios',
    status: 'published',
    featured: true,
    createdAt: '2025-01-19'
  }
];

// Event Categories
export const categories = [
  { id: 1, name: 'Technology', icon: '💻', color: '#667eea' },
  { id: 2, name: 'Business', icon: '💼', color: '#764ba2' },
  { id: 3, name: 'Arts', icon: '🎨', color: '#f5576c' },
  { id: 4, name: 'Entertainment', icon: '🎭', color: '#4facfe' },
  { id: 5, name: 'Health', icon: '🏥', color: '#43e97b' },
  { id: 6, name: 'Food', icon: '🍽️', color: '#fa709a' },
  { id: 7, name: 'Sports', icon: '⚽', color: '#00f2fe' },
  { id: 8, name: 'Education', icon: '📚', color: '#f093fb' }
];

// Helper Functions
export const getEventById = (id) => {
  return mockEvents.find(event => event.id === parseInt(id));
};

export const getEventsByCompany = (companyId) => {
  return mockEvents.filter(event => event.companyId === companyId);
};

export const getEventsByStatus = (status) => {
  return mockEvents.filter(event => event.status === status);
};

export const getFeaturedEvents = () => {
  return mockEvents.filter(event => event.featured && event.status === 'published');
};

export const getPublishedEvents = () => {
  return mockEvents.filter(event => event.status === 'published');
};

export const getUserById = (id) => {
  return mockUsers.find(user => user.id === parseInt(id));
};

export const getCompaniesByStatus = (status) => {
  return mockUsers.filter(user => user.role === 'company' && user.status === status);
};

export const formatDate = (dateString) => {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
};

export const getEventStatus = (event) => {
  const eventDate = new Date(event.date);
  const today = new Date();

  if (eventDate < today) {
    return 'past';
  } else if (event.registered >= event.capacity) {
    return 'full';
  } else {
    return 'upcoming';
  }
};

export const calculateProgress = (registered, capacity) => {
  return Math.round((registered / capacity) * 100);
};

export const getAllEvents = () => {
  return mockEvents;
};
